416-form-objects/signup/config/routes.rb
Example::Application.routes.draw do
  root to: 'users#index'

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :users
  resources :sessions
  resources :passwords
end

416-form-objects/signup/app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
end

416-form-objects/signup/app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_one :profile
end

416-form-objects/signup/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to login_url, alert: "Not authorized" if current_user.nil?
  end
end

416-form-objects/signup/app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
  def new
    @password_form = PasswordForm.new(current_user)
  end

  def create
    @password_form = PasswordForm.new(current_user)
    if @password_form.submit(params[:password_form])
      redirect_to current_user, notice: "Successfully changed password."
    else
      render "new"
    end
  end
end

416-form-objects/signup/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: "Logged in!"
    else
      flash.now.alert = "Email or password is invalid"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end
end

416-form-objects/signup/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @signup_form = SignupForm.new
  end

  def create
    @signup_form = SignupForm.new
    if @signup_form.submit(params[:user])
      session[:user_id] = @signup_form.user.id
      redirect_to @signup_form.user, notice: "Thank you for signing up!"
    else
      render "new"
    end
  end

  def show
    @user = current_user
  end
end

416-form-objects/signup/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Users</title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tag %>
  </head>
  <body>
    <div id="container">
      <% if current_user %>
        Logged in as <%= link_to current_user.username, user_path(current_user) %>.
        <%= link_to "Log Out", logout_path %>
      <% else %>
        <%= link_to "Sign Up", signup_path %> or
        <%= link_to "Log In", login_path %>
      <% end %>

      <% flash.each do |name, msg| %>
        <p><%= content_tag :div, msg, id: "flash_#{name}" %></p>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>